# These set of workflows run on every pull request
name: PR
on:
  pull_request:

permissions:
  contents: read

jobs:
  golangci-lint:
    uses: ./.github/workflows/golangci-lint.yml
  build:
    uses: ./.github/workflows/build.yml
  test:
    uses: ./.github/workflows/test.yml
